# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'FelixFastCatch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FelixFastCatch

pod 'WechatOpenSDK'
pod 'SnapKit', '~> 3.2.0'
pod 'Kingfisher', '~> 3.0'

end
