# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

# 指定 Master 仓库和阿里云仓库
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

target 'FelixFastCatch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

  # Pods for FelixFastCatch

pod 'WechatOpenSDK'
pod 'SnapKit', '~> 3.2.0'
pod 'Kingfisher', '~> 4.0'
pod 'Alamofire', '~> 4.4'
pod 'SVProgressHUD'
pod 'SwiftyJSON', '~> 3.1.4'
pod 'MJRefresh'
pod 'AgoraRtcEngine_iOS'
pod 'AlicloudFeedback', '~> 3.2.0'
pod 'Socket.IO-Client-Swift', '~> 12.0.0' # Or latest version
pod 'UMengAnalytics-NO-IDFA' #无IDFA版SDK
pod 'Bugly'

end
